---

- name: ClickHouse | Installing dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ clickhouse_required_packages }}"    

- name: ClickHouse | Install addon packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ clickhouse_addon_packages }}"

- name: ClickHouse | Add the APT Key for ClickHouse.
  apt_key:
    keyserver: "{{ clickhouse_key_server }}"
    id: "{{ clickhouse_id }}"
    state: present

- name: ClickHouse | Add ClickHouse APT sources
  apt_repository:
    repo: "{{ clickhouse_repo_url }}"
    state: present

- name: ClickHouse | Install ClickHouse
  apt:
    pkg:
      - clickhouse-server={{ clickhouse_version }}
      - clickhouse-client={{ clickhouse_version }}
      - clickhouse-common-static={{ clickhouse_version }}
  notify: Enable ClickHouse

- name: ClickHouse | Logrotate ClickHouse logs
  template:
    src: clickhouse.logrotate.j2
    dest: "/etc/logrotate.d/clickhouse"
    owner: root
    group: root
    mode: '0644'

- name: ClickHouse | Create non sensitive ClickHouse directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  loop:
    - "{{ clickhouse_conf_dir }}"

- name: ClickHouse | Create sensitive ClickHouse directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ clickhouse_user }}"
    group: "{{ clickhouse_group }}"
  loop:
    - "{{ clickhouse_path }}"
    - "{{ clickhouse_user_files_path }}"
    - "{{ clickhouse_access_control_path }}"
    - "{{ clickhouse_tmp_path }}"
    - "{{ clickhouse_log_directory }}"
