---
## General
clickhouse_version: 21.8.14.5

clickhouse_required_packages:
  - apt-transport-https
  - ca-certificates
  - dirmngr
  - gpg-agent

clickhouse_addon_packages:
  - mc
  - nano
  - htop
  - net-tools

# ClickHouse Key and Releases server
clickhouse_id: "E0C56BD4"
clickhouse_key_server: "hkp://keyserver.ubuntu.com:80"
clickhouse_repo_url: "deb https://repo.clickhouse.tech/deb/lts/ main/"

# Owner
clickhouse_group: clickhouse
clickhouse_user: clickhouse

# Files & Paths
clickhouse_path: /var/lib/clickhouse
clickhouse_tmp_path: "{{ clickhouse_path }}/tmp"
clickhouse_user_files_path: "{{ clickhouse_path }}/user_files"
clickhouse_access_control_path: "{{ clickhouse_path }}/access"
clickhouse_format_schema_path: "{{ clickhouse_path }}/format_schemas"
clickhouse_conf_dir: /etc/clickhouse-server
clickhouse_users_config: users.xml
# Logs
# clickhouse_loglevel: "information"  # More options: https://github.com/pocoproject/poco/blob/poco-1.9.4-release/Foundation/include/Poco/Logger.h#L105
clickhouse_loglevel: "error"
clickhouse_logs_rotation_size: "1000M"
clickhouse_logs_rotation_count: "10"
# clickhouse_log_directory: "{{ clickhouse_path }}/logs"
clickhouse_log_directory: "/var/log/clickhouse-server"
clickhouse_logs_conf: "{{ clickhouse_conf_dir }}/config.d/log-level.xml"

clickhouse_listen_host: 127.0.0.1
clickhouse_http_port: 8123
clickhouse_tcp_port: 9000
clickhouse_mysql_port: 9004
clickhouse_interserver_http_port: 9009

clickhouse_max_connections: 4096
clickhouse_keep_alive_timeout: 3
clickhouse_max_concurrent_queries: 5000 # 100

clickhouse_mlock_executable: true
clickhouse_max_server_memory_usage: 0
clickhouse_max_server_memory_usage_to_ram_ratio: 0.9
clickhouse_total_memory_profiler_step: 4194304
clickhouse_total_memory_tracker_sample_probability: 0
clickhouse_uncompressed_cache_size: 8589934592
clickhouse_mark_cache_size: 5368709120


clickhouse_default_user: "default"
clickhouse_default_pass: "PQLgT$9}"

clickhouse_default_profile: default
clickhouse_default_database: default
clickhouse_display_name: clickhouse-cluster-node
clickhouse_timezone: "Europe/Moscow"

clickhouse_internal_dns_disabled: 0

clickhouse_shard: "01"
clickhouse_cluster: clickhouse-cluster
clickhouse_distributed_cluster: distributed_cluster

clickhouse_profiles: # More settings: https://clickhouse.tech/docs/en/operations/settings/settings-profiles/
  default:
    max_memory_usage: 57982058496
    use_uncompressed_cache: 0
    load_balancing: "random"
    optimize_skip_unused_shards: 1
    background_pool_size: 64
    background_move_pool_size: 32
  reader:
    max_memory_usage: 8589934592
    use_uncompressed_cache: 0
    load_balancing: "random"      
    readonly: 1
  writer:    
    max_memory_usage: 8589934592
    use_uncompressed_cache: 0
    load_balancing: "random"  

clickhouse_quotas: # More settings: https://clickhouse.tech/docs/en/operations/quotas/
  default:
    intervals:
      - duration: 3600
        queries: 0
        errors: 0
        result_rows: 0
        read_rows: 0
        execution_time: 0    

# # If Enable IPv6 on server
# clickhouse_networks_default:
#   - "::0"

# # If Enable IPv6 on server
# clickhouse_listen_addresses:
#   - "::0"
#   - "127.0.0.1"

# clickhouse_listen_addresses: "{{ clickhouse_networks_default }}"

# https://stackoverflow.com/questions/46730012/connecting-to-clickhouse-on-remote-server-fails-with-weird-address
clickhouse_networks_default: '::/0'
clickhouse_listen_addresses: '::'


# More settings: https://clickhouse.tech/docs/en/operations/settings/settings-users/
clickhouse_users:
  default:
    password: "{{ clickhouse_default_pass }}"
    profile: "default"
    quota: "default"
    networks: "{{ clickhouse_networks_default }}"    
  reader:
    password: "8w_D?aTa"
    profile: "reader"
    quota: "default"
    networks: "{{ clickhouse_networks_default }}"
  writer:
    password: "+?ps9Ybn"
    profile: "writer"
    quota: "default"      
    networks: "{{ clickhouse_networks_default }}"  

clickhouse_zookeeper_port: 2181
